/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package shoppingsystem;

/**
 *
 * @author BitCom Tech
 */
public class CustomerDashboard extends javax.swing.JFrame {

    /**
     * Creates new form CustomerLogin
     */
    public CustomerDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        customer_name = new javax.swing.JLabel();
        custumer_id = new javax.swing.JLabel();
        edit_profile_btn = new javax.swing.JButton();
        edit_profile1 = new javax.swing.JButton();
        edit_profile2 = new javax.swing.JButton();
        customer_name1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        customer_name.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        customer_name.setForeground(new java.awt.Color(0, 102, 0));
        customer_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        customer_name.setText("Products");

        custumer_id.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        custumer_id.setForeground(new java.awt.Color(0, 102, 0));
        custumer_id.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        custumer_id.setText("ID: CUS/12334/24");

        edit_profile_btn.setBackground(new java.awt.Color(0, 102, 0));
        edit_profile_btn.setForeground(new java.awt.Color(255, 255, 255));
        edit_profile_btn.setText("Edit Profile");
        edit_profile_btn.setBorderPainted(false);
        edit_profile_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_profile_btnActionPerformed(evt);
            }
        });

        edit_profile1.setBackground(new java.awt.Color(0, 102, 0));
        edit_profile1.setForeground(new java.awt.Color(255, 255, 255));
        edit_profile1.setText("view cart");
        edit_profile1.setBorderPainted(false);
        edit_profile1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_profile1ActionPerformed(evt);
            }
        });

        edit_profile2.setBackground(new java.awt.Color(0, 102, 0));
        edit_profile2.setForeground(new java.awt.Color(255, 255, 255));
        edit_profile2.setText("add to cart");
        edit_profile2.setBorderPainted(false);
        edit_profile2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_profile2ActionPerformed(evt);
            }
        });

        customer_name1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        customer_name1.setForeground(new java.awt.Color(0, 102, 0));
        customer_name1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        customer_name1.setText("CustomerName");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edit_profile_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(custumer_id, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(edit_profile1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(edit_profile2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(customer_name, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(378, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(441, Short.MAX_VALUE)
                    .addComponent(customer_name1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(2, 2, 2)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edit_profile1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edit_profile2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(custumer_id, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(edit_profile_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(customer_name, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(355, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(33, 33, 33)
                    .addComponent(customer_name1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(475, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void edit_profile_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_profile_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edit_profile_btnActionPerformed

    private void edit_profile1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_profile1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edit_profile1ActionPerformed

    private void edit_profile2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_profile2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edit_profile2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
  
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CustomerDashboard().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel customer_name;
    public javax.swing.JLabel customer_name1;
    private javax.swing.JLabel custumer_id;
    private javax.swing.JButton edit_profile1;
    private javax.swing.JButton edit_profile2;
    private javax.swing.JButton edit_profile_btn;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
